# Generated by Django 4.0.3 on 2022-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_salesrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
