# Generated by Django 4.0.3 on 2022-08-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_salesrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
