# Generated by Django 4.0.3 on 2022-08-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appt_date',
        ),
    ]
