# Generated by Django 4.0.3 on 2022-08-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_serviceappointment_appt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='appt_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='appt_time',
            field=models.TimeField(null=True),
        ),
    ]
