# Generated by Django 4.0.3 on 2022-08-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_serviceappointment_appt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appt_date',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appt_time',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='appt_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
